export const POKEMONS_PENDING = 'POKEMONS_PENDING';
export const POKEMONS_SUCCESS = 'POKEMONS_SUCCESS';
export const POKEMONS_ERROR = 'POKEMONS_ERROR';
export const POKEMON_PENDING = 'POKEMON_PENDING';
export const POKEMON_SUCCESS = 'POKEMON_SUCCESS';
export const POKEMON_ERROR = 'POKEMON_ERROR';
export const FILTER_TYPE = 'FILTER_TYPE';
